# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f15952d5214389709364006740466d2597ecb6953341efc71d089050e5f3a26c2bac06f854c492274f8bc714f08502efbca134aa1784ddaba732d73eee7c2d80

test:
  secret_key_base: 216f11782c629ba94b7e20052897a14bf9f0651b8c1a69a696c131772f9be9e7242e0939ac95da354baaa0093f1312c6747eefb88d0999777e06e62f31d97c1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
